version: 0.2

phases:
  install:
    commands:
      - sudo yum install git

  pre_build:
    commands:
      - git --version
      - git clone https://github.com/accawsdevops/25novCodeBuild.git

  build:
    commands:
      - git branch -r

  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files:
    - 'index.html'
